import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import HxouseLogo from '../public/hxouse.svg'
import styles from '../components/Essentials.module.css'
import Grid from '@react-css/grid'
import {
	Navbar,
	Container,
	Nav,
	NavDropdown
} from 'react-bootstrap';

export default function About() {
  return (

<div className={styles.container_fluid}>
  <Head>
    <title>About.</title>
    <meta name="description" content="Generated by create next app" />
		<meta name="description" content="Web Application for hldtru®" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
		<link rel="manifest" href="/site.webmanifest" />
  </Head>


	<Navbar fixed="top" bg="transparent" expand="md" className="Navbar">
	  <Container>
	    <Navbar.Brand href="/"><Image src={HxouseLogo} alt="hxouse.logo" srcSet="0.5x" /></Navbar.Brand>
	    <Navbar.Toggle aria-controls="navbar-toggler" />
	    <Navbar.Collapse id="basic-navbar-nav">
	      <Nav className="me-auto">
	        <Nav.Link href="#home">Home</Nav.Link>
	        <Nav.Link href="#link">Link</Nav.Link>
	        <NavDropdown title="Webstore" id="basic-nav-dropdown">
	          <NavDropdown.Item href="#action/3.1">New</NavDropdown.Item>
	          <NavDropdown.Item href="#action/3.2">Shorts</NavDropdown.Item>
	          <NavDropdown.Item href="#action/3.3">Tees</NavDropdown.Item>
	          <NavDropdown.Divider />
	          <NavDropdown.Item href="#action/3.4">Separated link</NavDropdown.Item>
	        </NavDropdown>
	      </Nav>
	    </Navbar.Collapse>
	  </Container>
	</Navbar>

<div className={styles.container}>


		<Grid>
				<Grid.Item columnStart={2} columnEnd={5}>
				<p className="h4">About the Brand.</p>
				<p>
						<small>
							 <i><strong>hldtru</strong></i>® _ is an East Coast based design label. Our only mission is to push truth in everything. The only desire is to be fully in our truth, creating true happiness.
								<br />
								<br />
								</small>
				</p>

				<br />
				<br />

				<Grid className={styles.grid_gap} gap='2em'></Grid>

				<Grid className={styles.grid_align_center} alignItems='center'>
				<p>
				Copyright © 2021. All rights reserved.
				</p>
				<p>Power in <i><strong>Truth</strong></i>®</p>
				</Grid>




				</Grid.Item>
		</Grid>



		<footer className={styles.footer}>
				<Link href="/">
						<a>Contact</a>
				</Link>

				<Link href="/">
						<a>Terms & Conditions</a>
				</Link>

				<a href="https://instagram.com/hldtru" target="_blank" rel="noreferrer">
						Instagram
				</a>
		</footer>
 </div>
 </div>
 )
}
