import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import HxouseLogo from '../public/hxouse.svg'
import styles from '../components/Essentials.module.css'
import Grid from '@react-css/grid'
import {
	Navbar,
	Container,
	Nav,
	NavDropdown
} from 'react-bootstrap';
import {
	ChakraProvider,
	Box,
	Center,
	Text,
	Heading,
	Skeleton,
	Menu,
	MenuButton,
	Button,
	MenuList,
	MenuOptionGroup,
	MenuItem,
	MenuDivider,
	Portal,
	Stack,
	Badge,
} from "@chakra-ui/react"



export default function About() {
  return (

<div className={styles.container_fluid}>
  <Head>
    <title>About.</title>
    <meta name="description" content="Generated by create next app" />
		<meta name="description" content="Web Application for hldtru®" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="icon" href="/favicon.ico" />
		<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
		<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
		<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
		<link rel="manifest" href="/site.webmanifest" />
  </Head>

<ChakraProvider>
  <Menu className={styles.menu}>
    <Box
      pos="fixed"
      zIndex={20}
      top="0"
      bg="white"
      w="100%"
      p={3}
      color="white"
    >
      <Stack direction="row">
        <Badge
          as="button"
          variant="outline"
          colorScheme="gray"
          onClick={() => router.back()}
        >
          Back
        </Badge>
        <Badge as="button">
          <Link href="https://hldtru.us/" target="_blank" rel="norefferer">
            Webstore
          </Link>
        </Badge>
        <Badge
          as="button"
          href="https://chakra-ui.com"
          target="_blank"
          rel="norefferer"
        >
          Archive
        </Badge>
        <Badge as="button" href="/archive" target="_blank" rel="norefferer">
          Cart
        </Badge>
      </Stack>
    </Box>
  </Menu>
</ChakraProvider>

<div className={styles.container}>
		<Grid>
				<Grid.Item columnStart={2} columnEnd={5}>
				<p className="h4">About the Brand.</p>
				<p>
						<small>
							 <i><strong>hldtru</strong></i>® _ is an East Coast based design label. Our only mission is to push truth in everything. The only desire is to be fully in our truth, creating true happiness.
								<br />
								<br />
								</small>
				</p>




				</Grid.Item>
		</Grid>



		<footer className={styles.footer}>
				<Link href="/">
						<a>Contact</a>
				</Link>

				<Link href="/">
						<a>Terms & Conditions</a>
				</Link>

				<a href="https://instagram.com/hldtru" target="_blank" rel="noreferrer">
						Instagram
				</a>
		</footer>
 </div>
 </div>
 )
}
