import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Early.module.css'


export default function Early() {
  return (

<div className={styles.container}>
      <Head>
       <title>Early Access</title>
       <meta name="description" content="Generated by create next app" />
       <link rel="icon" href="/favicon.ico" />
      </Head>


  <div className={styles.footer}>
    <a href="">Contact</a>
    <a href="">Terms & Conditions</a>
    <a href="https://instagram.com/hldtru" rel="norefferer" target="_blank">Instagram</a>
  </div>
	</div>
) }
